# fly.toml app configuration file generated for new-service on 2023-08-20T16:30:23-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "new-service"
primary_region = "mia"

[build]

[http_service]
internal_port = 3000
force_https = true
auto_stop_machines = true
min_machines_running = 0
[http_service.concurrency]
type = "requests"
soft_limit = 30
hard_limit = 35
